# Generated by Django 2.0.6 on 2018-06-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('hr_ini', models.TimeField()),
                ('hr_fim', models.TimeField()),
                ('priori', models.BooleanField()),
            ],
        ),
    ]
